#!/usr/bin/env bash
# One-command validation of the CBACT04C pilot. Runs, in order:
#   run-parity.sh (frozen clock), run-parity-live.sh (real clock, timestamps masked),
#   run-sample.sh on app/data/ASCII (frozen + real clock) vs the COBOL baseline of sample-raw,
#   check-quirks.py on the COBOL baselines and the Java outputs, mutation-check.sh, mvn test.
# Writes parity/RESULTS.md from the fresh outputs; logs go to parity/out/logs/.
# Exits 1 if any step fails. Requires cobc (GnuCOBOL 3.x), Java 17, Maven, python3.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
MOD="$(cd "$HERE/.." && pwd)"
cd "$HERE"
LOG="$(mktemp -d)"
declare -A RES
status=0
step() {
  local name="$1"; shift
  if "$@" > "$LOG/$name.log" 2>&1; then RES[$name]=PASS; else RES[$name]=FAIL; status=1; fi
  echo "${RES[$name]}  $name"
}
sample_vs_cobol() {  # $1 = frozen|live
  local out="out/sample-$1" mask=""
  [ "$1" = live ] && mask="--mask-timestamps"
  rm -rf "$out"
  if [ "$1" = frozen ]; then "$MOD/run-sample.sh" "$out/run" 2022071800 2022-07-18T01:02:03.45
  else "$MOD/run-sample.sh" "$out/run"; fi
  echo $? > "$out/run/rc"
  mkdir -p "$out/java/sample-raw" "$out/cobol"
  cp "$out/run/"{transact.dat,acctdata.txt,sysout.txt,rc} "$out/java/sample-raw/"
  ln -s "$HERE/scenarios/sample-raw/expected" "$out/cobol/sample-raw"
  ./compare.py $mask "$out/cobol" "$out/java" "$out/RESULTS.md"
}

step parity ./run-parity.sh
step live ./run-parity-live.sh
./compare.py out/live/cobol out/live/java > "$LOG/live-unmasked.log" 2>&1
step sample-frozen sample_vs_cobol frozen
step sample-live sample_vs_cobol live
step quirks bash -c './check-quirks.py --md out/cobol out/java > out/quirks.md'
step mutation ./mutation-check.sh
step mvn-test bash -c "cd '$MOD' && mvn -B test"
mkdir -p out/logs; cp "$LOG"/*.log out/logs/; rm -rf "$LOG"

export STATUS_PARITY="${RES[parity]}" STATUS_LIVE="${RES[live]}" STATUS_SF="${RES[sample-frozen]}" \
       STATUS_SL="${RES[sample-live]}" STATUS_Q="${RES[quirks]}" STATUS_MUT="${RES[mutation]}" \
       STATUS_MVN="${RES[mvn-test]}"
export V_COBC="$(cobc --version | head -1)" V_JAVA="$(java -version 2>&1 | head -1)" \
       V_MVN="$(mvn -B -v | head -1 | sed -e 's/\x1b\[[0-9;]*m//g' -e 's/ (.*//')" V_PY="$(python3 --version)" \
       V_SHA="$(git -C "$MOD" rev-parse --short HEAD)" \
       V_DIRTY="$(git -C "$MOD" status --porcelain -- . ':!parity/RESULTS.md' | wc -l)"
python3 - <<'PY'
import os, re
from datetime import datetime, timezone
from pathlib import Path
E = os.environ
out = Path("out")
def summary(p):  # first table of a compare.py report
    return Path(p).read_text().split("\n\n")[0].strip()
def ok(s): return "pass" if E[s] == "PASS" else "**FAIL**"
scen = sorted(p.name for p in Path("scenarios").iterdir() if p.is_dir())
tot = {"transact": 0, "acct": 0, "sysout": 0}
for s in scen:
    d = Path("scenarios") / s / "expected"
    tot["transact"] += d.joinpath("transact.dat").stat().st_size // 350
    tot["acct"] += len(d.joinpath("acctdata.txt").read_text().splitlines())
    tot["sysout"] += len(d.joinpath("sysout.txt").read_text().splitlines())
frozen = summary(out / "RESULTS-frozen.md")
live = summary(out / "live/RESULTS.md")
n_frozen = frozen.count("| identical |"); n_live = live.count("| identical |")
unmasked = len(re.findall(r"^DIFF", (out / "logs/live-unmasked.log").read_text(), re.M))
par = (out / "logs/parity.log").read_text()
orc = par.split("--- oracle vs COBOL baseline")[1].split("--- oracle vs Java")[0]
oj = par.split("--- oracle vs Java")[1]
o_cobol = len(re.findall(r"^MATCH", orc, re.M)); o_java = len(re.findall(r"^MATCH", oj, re.M))
mvn = (out / "logs/mvn-test.log").read_text()
classes = re.findall(r"Tests run: (\d+), Failures: (\d+), Errors: (\d+), Skipped: (\d+).*? in (\S+)", mvn)
total = re.findall(r"^\[\w+\] Tests run: (\d+), Failures: (\d+), Errors: (\d+), Skipped: (\d+)\s*$", mvn, re.M)
mut = (out / "logs/mutation.log").read_text().strip()
sf, sl = summary(out / "sample-frozen/RESULTS.md"), summary(out / "sample-live/RESULTS.md")
sample_row = lambda t: t.splitlines()[2]
dirty = f" plus {E['V_DIRTY']} uncommitted file(s)" if E["V_DIRTY"] != "0" else ""
mvn_total = total[-1] if total else ("?",) * 4
L = [
"# CBACT04C parity results", "",
f"Generated by `parity/validate.sh` on {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC from commit `{E['V_SHA']}`{dirty}.",
f"Toolchain: {E['V_COBC']}; {E['V_JAVA']}; {E['V_MVN']}; {E['V_PY']}.", "",
"## Summary", "",
"| Check | Scenarios | Result |", "|---|---:|---|",
f"| COBOL vs Java, frozen clock (`run-parity.sh`) | {n_frozen} / {len(scen)} identical | {ok('STATUS_PARITY')}: {tot['transact']:,} TRANSACT records, {tot['acct']:,} ACCTFILE records, {tot['sysout']:,} SYSOUT lines, all return codes |",
f"| COBOL vs Java, real clock, timestamps masked (`run-parity-live.sh`) | {n_live} / {len(scen)} identical | {ok('STATUS_LIVE')}; unmasked, {unmasked} scenarios differ (the clock was live) |",
f"| Oracle vs COBOL baseline (`oracle.py`) | {o_cobol} / {len(scen)} byte-identical | {ok('STATUS_PARITY')} |",
f"| Oracle vs Java (`oracle.py --against out/java`) | {o_java} / {len(scen)} byte-identical | {ok('STATUS_PARITY')} |",
f"| `run-sample.sh` on `app/data/ASCII`, frozen clock, vs COBOL `sample-raw` | 1 / 1 | {ok('STATUS_SF')} |",
f"| `run-sample.sh` on `app/data/ASCII`, real clock, timestamps masked, vs COBOL `sample-raw` | 1 / 1 | {ok('STATUS_SL')} |",
f"| Quirk checks (`check-quirks.py`) on COBOL baselines and Java outputs | {len(scen)} | {ok('STATUS_Q')} |",
f"| `mvn test` (GoldenParityTest + unit tests) | | {ok('STATUS_MVN')}: {mvn_total[0]} tests, {mvn_total[1]} failures, {mvn_total[2]} errors, {mvn_total[3]} skipped |",
f"| Mutation check (`mutation-check.sh`) | | {ok('STATUS_MUT')}: every rounding mutant detected |", "",
"## Per-scenario counts, frozen clock", "",
"COBOL record counts; a cell shows `COBOL / Java` only if the counts differ. rc 231 is the CEE3ABD abend (U999).", "",
frozen, "",
"## Per-scenario counts, real clock (timestamps masked)", "", live, "",
"## `run-sample.sh` on the shipped `app/data/ASCII`", "",
"| Run | TRANSACT records | ACCTFILE records | SYSOUT lines | rc COBOL | rc Java | Result |", "|---|---:|---:|---:|---:|---:|---|",
sample_row(sf).replace("| sample-raw |", "| frozen clock |", 1),
sample_row(sl).replace("| sample-raw |", "| real clock, timestamps masked |", 1), "",
"## Quirks reproduced (counts over all scenarios)", "",
Path(out / "quirks.md").read_text().strip().replace("| Check | cobol | java |", "| Check | COBOL baseline | Java port |"), "",
"## Mutation check", "", "```", mut, "```", "",
"## `mvn test`", "", "| Test class | Tests | Failures | Errors | Skipped |", "|---|---:|---:|---:|---:|",
*[f"| {c[4].split('.')[-1]} | {c[0]} | {c[1]} | {c[2]} | {c[3]} |" for c in classes], "",
"## Per-artifact comparison, frozen clock", "",
(out / "RESULTS-frozen.md").read_text().split("\n\n", 1)[1].strip(), "",
]
Path("RESULTS.md").write_text("\n".join(L))
PY
echo "wrote $HERE/RESULTS.md"
exit $status
