package com.carddemo.interest;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.io.TempDir;

/**
 * Replays every scenario in {@code parity/scenarios} and checks the Java outputs against the
 * baseline produced by the original COBOL under GnuCOBOL ({@code expected/}, generated by
 * {@code parity/run-parity.sh}). Byte-for-byte: TRANSACT, the updated ACCTFILE, SYSOUT and the
 * return code.
 */
class GoldenParityTest {

    private static final Path SCENARIOS = Path.of("parity", "scenarios");

    @TempDir
    Path tmp;

    @TestFactory
    Stream<DynamicTest> javaMatchesCobolBaseline() throws IOException {
        List<Path> scenarios = new ArrayList<>();
        try (Stream<Path> dirs = Files.list(SCENARIOS)) {
            dirs.filter(d -> Files.isDirectory(d.resolve("expected"))).sorted().forEach(scenarios::add);
        }
        assertFalse(scenarios.isEmpty(), "no scenarios with an expected/ baseline under " + SCENARIOS);
        return scenarios.stream().map(s -> DynamicTest.dynamicTest(s.getFileName().toString(), () -> replay(s)));
    }

    private void replay(Path scenario) throws IOException {
        Path work = Files.createDirectories(tmp.resolve(scenario.getFileName().toString()));
        for (String f : List.of("tcatbal.txt", "cardxref.txt", "acctdata.txt", "discgrp.txt")) {
            Files.copy(scenario.resolve("input").resolve(f), work.resolve(f));
        }
        for (String dd : setting(scenario, "missing", "").split("\\s+")) {
            String file = switch (dd) {
                case "TCATBALF" -> "tcatbal.txt";
                case "XREFFILE" -> "cardxref.txt";
                case "ACCTFILE" -> "acctdata.txt";
                case "DISCGRP" -> "discgrp.txt";
                default -> null;
            };
            if (file != null) {
                Files.delete(work.resolve(file));
            }
        }
        LocalDateTime now = LocalDateTime.parse(setting(scenario, "timestamp", "2022-07-18T01:02:03.45"));
        ByteArrayOutputStream sysout = new ByteArrayOutputStream();
        JobFiles files = new JobFiles(work.resolve("tcatbal.txt"), work.resolve("cardxref.txt"),
                work.resolve("acctdata.txt"), work.resolve("discgrp.txt"), work.resolve("transact.dat"));
        int rc = new InterestCalculator(files, setting(scenario, "parm", "2022071800"), () -> now,
                new PrintStream(sysout, true, StandardCharsets.ISO_8859_1)).run();

        Path expected = scenario.resolve("expected");
        assertEquals(Files.readString(expected.resolve("rc")).trim(), Integer.toString(rc & 0xFF), "return code");
        assertArrayEquals(Files.readAllBytes(expected.resolve("sysout.txt")), sysout.toByteArray(), "SYSOUT");
        assertArrayEquals(Files.readAllBytes(expected.resolve("transact.dat")), readOrEmpty(work.resolve("transact.dat")),
                "TRANSACT");
        assertArrayEquals(Files.readAllBytes(expected.resolve("acctdata.txt")), readOrEmpty(work.resolve("acctdata.txt")),
                "ACCTFILE");
    }

    private static String setting(Path scenario, String name, String defaultValue) throws IOException {
        Path p = scenario.resolve(name);
        return Files.exists(p) ? Files.readString(p).trim() : defaultValue;
    }

    private static byte[] readOrEmpty(Path p) throws IOException {
        return Files.exists(p) ? Files.readAllBytes(p) : new byte[0];
    }
}
